# Generated by Django 2.1.5 on 2019-01-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_collection', '0002_auto_20190107_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='drawing',
            field=models.ImageField(upload_to='./static'),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(upload_to='./static'),
        ),
        migrations.AlterField(
            model_name='item',
            name='transcription',
            field=models.ImageField(upload_to='./static'),
        ),
    ]
