# Generated by Django 2.1.5 on 2019-02-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_collection', '0004_auto_20190211_0150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='notes',
            new_name='description',
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField(default='dpi', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='material_type',
            field=models.CharField(default='ZA=stone vessels', max_length=100),
            preserve_default=False,
        ),
    ]
