# Generated by Django 2.1.5 on 2019-02-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_collection', '0005_auto_20190211_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='material_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
